### ISSUE TITLE
Access cjpeg 

### ISSUE THREAD

**Issue by henri-hulski** [wanadev/mozjpeg-lossless-optimization#1]
Hi! 
Looks quite interesting.
Is it also possible to access cjpeg to create new images?

**Comment by flozz** [comment]
Hello,

Accessing cjpeg is out of the scope of this library (too much work and the cjpeg API is messy / too complicated (IMHO)).

With Python, the simplest way to create JPEGs is probably using [Pillow](https://pillow.readthedocs.io/en/stable/).

:)

**Comment by henri-hulski** [comment]
Thanks for your answer?
At the moment I'm using mozjpeg cjpeg directly from the system.
But this is not really compatible when I make a web app for someone else when I don't know his server.
So you would suggest to create the image with pillow and optimize it after with this app?

**Comment by henri-hulski** [comment]
Thanks!
I will try. :)
