### ISSUE TITLE
Linux arm builds

### ISSUE THREAD

**Issue by axu2** [wanadev/mozjpeg-lossless-optimization#23]
Looks like GitHub will add Linux ARM64 runners this year, 

https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/

https://github.com/github/roadmap/issues/970

**Comment by flozz** [comment]
Hello,

I am not sure on how to use the new arm64 runners but it is already possible to build for this architecture using qemu:

* https://cibuildwheel.pypa.io/en/stable/faq/#emulation

I will try to have a look at this when I have some time :)

**Comment by axu2** [comment]
Thanks! While we are at it, can you add armv7 too?

**Comment by flozz** [comment]
I tried for ARMv7 but I had the following error:

    ValueError: 'armv7l' is not a valid Architecture

cibuildwheel lists this architecture in their table... but only for musllinux target (that's maybe why it failed):

* https://cibuildwheel.pypa.io/en/stable/

I don't searched further but if you have info on how to make the build for this arch I could have a look. :)

**Comment by axu2** [comment]
I think you need to bump the cibuildwheel version too.

https://github.com/pypa/cibuildwheel/pull/2017#issuecomment-2394961256

**Comment by flozz** [comment]
v1.1.4 released, the build of the wheels is in progress and should be available soon. The ARM64 wheels for Linux will be available at the same time.

I close this ticket as it is resolved. Maybe you can open an other one for the armv7 target if it matter :)
