### ISSUE TITLE
mozjpeg 4.1.1

### ISSUE THREAD

**Issue by ivanionut** [wanadev/mozjpeg-lossless-optimization#3]
hi @wanadev 
version 4.1.1 of mozjpeg has just been released:
https://github.com/mozilla/mozjpeg/releases/tag/v4.1.1

when you can, can you update your python library too?

thanks 😃

**Comment by flozz** [comment]
Hello,

Thank you for warning us about the updates of MozJPEG. :)

I updated to MozJPEG latest commit on `master`. Packages are being built by the CI and will be published soon (v1.1.0).
